# -*- coding: utf-8 -*-
"""04.03.2024-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzxiwVRf6ptgS5BwGz02PVx9U2iC3FGW

1:
"""

lista = []
print(type(lista))
for i in range (1, 6):
  lista.append(int(input()))

for idx, item in enumerate(lista):
  print(f'{idx}:{item}')

"""2. Ler uma lista de 10 numeros reais e mostre-os na ordem inversa que foram lidos"""

lista = []
for i in range(10):
  lista.append(int(input()))

inversa = lista[::-1]
print(inversa)

"""3. Ler uma lista com 5 idades e exibir a maior e a menor"""

idade = []
for i in range(5):
  idade.append(int(input()))
print(f"idade maxima é: {max(idade)}")
print(f"idade minima é: {min(idade)}")

"""4. Inicialize uma lista de 10 numeros inteiros. Armezene os numeros pares em uma lista PAR e os numeros impares em uma lista IMPAR.
Imprima as listas PAR e IMPAR.
"""

lista = list(range(20))
PAR = [x for x in lista if x % 2 == 0]
print(PAR)
IMPAR = [x for x in lista if x % 2 == 1]
print(IMPAR)

"""5.Escreva um programa que troque o primeiro com o ultimo elemento de uma lista qualquer."""

lista = list(range(10))
intermediario = lista[-1]
lista[-1] = lista [0]
lista[0] = intermediario
print(lista)

"""6. Qual a saída/resultado da seguinte compreensão de lista?
Você consegue entender e explicar o resultado?
"""

[[1 + j*3 + i for i in range(3)] for j in range(3)]
# O que ocorre nesse código é um calculo em que dois valores são constantemente alterados por dois laços de repetição, onde o laço exterior (que é executado três vezes) a cada execução executa o laço interior três vezes, passando ambos os laços por 0, 1 e 2. O resultado apresentado são os valores do calculo com base nos seguintes valores inseridos: (j = 0 i =0,1,2), (j = 1 i =0,1,2), (j = 2 i =0,1,2)

"""7. Considere que você recebe um dicionário contendo informações sobre produtos em
uma loja. Cada chave do dicionário é o nome de um produto e cada valor é uma tupla
contendo o preço e a quantidade em estoque desse produto.
Você deve criar um programa em Python que solicite ao usuário que insira um preço
máximo. Em seguida, o programa deve imprimir os produtos cujo preço seja menor ou
igual ao preço máximo inserido pelo usuário.
"""

produtos = {
    'camisa' : (25.00 , 10),
    'calça' : (60.00 , 8),
    'jaqueta' : (120.00 , 10),
    'tenis' : (300.00 , 5),
    'meia' : (10.00 , 15)
}

valor = int(input("Insira o valor máximo: "))

for i, p in produtos.items():
  preco = p[0]
  #print(preco)
  if preco <= valor:
    print(f"Produto: {i} Valor: {preco}")

"""8. Em uma competição de ginástica, cada atleta recebe votos de
sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica
sendo a média dos votos restantes. Você deve fazer um programa
que receba o nome do ginasta e as notas dos sete jurados
alcançadas pelo atleta em sua apresentação e depois informe a sua
média, conforme a descrição acima informada (retirar o melhor e o
pior salto e depois calcular a média com as notas restantes). As
notas não são informadas em ordem crescente ou decrescente.
"""

ginasta = {}
ginasta['notas'] = []
ginasta['nome'] = input("Insira o nome do ginasta: ")
for i in range(1,8):
  ginasta['notas'].append(int(input(f"Insira a nota {i}:")))
ginasta['notas'].remove(max(ginasta['notas']))
ginasta['notas'].remove(min(ginasta['notas']))

print(f"A média de {ginasta['nome']} foi: {sum(ginasta['notas']) / len(ginasta['notas'])}")
#print(ginasta)0