# -*- coding: utf-8 -*-
"""04.03.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OlNl9fA5IoA_tmfUmMrsXuT97UMYsdfk
"""

programadores = ['vitor', 'aline', 'ana', 'camile', 'gustavo']
print(len(programadores)) #tamanho da lista
print(type(programadores)) #tipo da lista
print(programadores[3])  #posicao da lista
print(programadores[-1]) #ultimo indice da lista
print(programadores)
print(programadores[::-1]) #inverte a lista, :: significa passo
programadores[4] = 'vinicius' #substitui o valor do indice 4
print( programadores)
programadores.append('gustavo') #soma ao final da lista
print(programadores)
programadores.insert(1, 'charlie') #insere na posicao 1, sem sobrescrever o anterior
print(programadores)

programadores = programadores + ['toro'] #soma duas listas
print(programadores)

programadores = ['toro'] + programadores #soma duas listas, ao contrario
print(programadores)

print(programadores[:4] + programadores[4:]) #seleciona uma parte da lista, parte ela em dois
print(programadores[:4] + ['butantan'] + programadores[4:]) #soma um valor no meio da lista

#sum(programadores) #soma os valores da lista
#programadores.remove(2) #remove indice 3
programadores.remove('vitor') #remove victor da lista, em caso haja mais de um ele remove o primeiro que encontrar
programadores.pop(0) #remove o indice 0, se não passado o parametro ele remove do final da lista

print(programadores)
last = programadores.pop(-1) #remove o ultimo valor e o salva
print(programadores)
print(last) #valor removido

print(programadores.sort()) #ordena em crescente
print(programadores.reverse()) #ordena em decrescente

aluno = ['Vinicius', 19, 1.75]

#TUPLAS
numeros = ('1', '2', '3') #imutavel
obj_string = ("aa") #string
obj_tupla = ("aa",) #tupla

print(min(numeros)) #valor minimo
print(max(numeros)) #valor maximo

numeros2 = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(sum(numeros2) / len(numeros2)) #calculo de media de uma lista

#LIST COMPREHENSION

quadrados = [X ** 2 for X in range(1, 11)]
print(quadrados) #NUMEROS AO QUADRADO

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9 ,10]
pares = [x for x in numeros if x % 2 == 0]
print(pares) #NUMEROS PARES

palavras = ["Olá", "Mundo"]
upper = [word.upper() for word in palavras]
print(upper) #PALAVRAS CAIXA ALTA


#DICIONARIO
aluno = {
    'nome' : 'Vinicius',
    'idade' : 20,
    'curso' : 'Ciência de Dados',
    'notas' : {'matematica' : 10, 'biologia' : 10, 'quimica' : 10}
}

print(aluno['nome'])

for chave in aluno: #imprime todas as chaves do dicionario
  print(chave)

for chave, valor in aluno.items(): #imprime as chaves e valores do dicionario
  print(chave, ":", valor)

for valor in aluno.items(): #imprime as chaves e valores do dicionario, mas como foi passado uma unica variavel ele cria uma TUPLA
  print( valor)

for valor in aluno['notas'].items(): #imprime as chaves e valores do dicionario, mas como foi passado uma unica variavel ele cria uma TUPLA
  print( valor)

turma ={
    1: {'nome' : 'Marcos', 'idade' : 20, 'notas': {'matematica' : 10, 'fisica' : 9}},
    2: {'nome' : 'Jose', 'idade' : 22, 'notas': {'matematica' : 10, 'fisica' : 8}},
    3: {'nome' : 'Josefina', 'idade' : 25, 'notas': {'matematica' : 9, 'fisica' : 10}},
    4: {'nome' : 'Victor', 'idade' : 21, 'notas': {'matematica' : 8, 'fisica' : 6}},
    5: {'nome' : 'Ana', 'idade' : 23, 'notas': {'matematica' : 10, 'fisica' : 9}}
}

for valor in turma:
  print(turma[valor]['nota'])