# -*- coding: utf-8 -*-
"""06.03.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1opYIH_z9rU8YQKR0I0fx3lIU1YUb8zCg
"""

#def funcao(nome):
#  abcde

#funcao(nome)

def saudacao(nome):
  print(f"Olá {nome}")

nome = input("Entre seu nome:")

saudacao(nome)

def alterna(n):
  mult = 1
  for i in range(n+1):
    mult *= -1
    i *= mult
    print(i, end=' ')

alterna(6)

def area_triangulo(base, altura):
  area = base * altura / 2
  return area

#triangulo 1
base1 = 2 #cm
altura1 = 5

#triangulo 2
base2= 4
altura2= 5

print(f"Area triangulo 1 = {area_triangulo(base1, altura1)} cm*cm")
print(f"Area triangulo 1 = {area_triangulo(base2, altura2)} cm*cm")

def perimetro_retangulo(a, b):
  perimetro = (2*a) + (2*b)
  return perimetro

print(perimetro_retangulo(2,3))

def saudacao(nome, mensagem):
  #print(f"Olá, {nome}! {mensagem}")
  print("Olá,", nome,"!", mensagem)

#parametros posicionais
saudacao("Vinicius", "Tudo bem?")

#parametro nomeado
saudacao(mensagem="Bem e você?", nome="Ana")

def saudacao(nome, mensagem = "Bom dia!"):
  #print(f"Olá, {nome}! {mensagem}")
  print("Olá,", nome,"!", mensagem)

#parametros posicionais
saudacao("Vinicius")

#parametro nomeado
saudacao(mensagem="Tudo bem com você?", nome="Ana")

def soma_pn(valores):
  soma_p = 0 #positivos
  soma_n = 0 #negativos
  for n in valores:
    if n > 0:
      soma_p += n
    elif n < 0:
      soma_n += n

  return soma_p, soma_p

valores = [2, -1, 3, -4]
soma_p, soma_n = soma_pn(valores)
print(f"soma dos positivos é: {soma_p} e soma dos negativos é: {soma_n}")

x = [1, 2, 3]
def somas(lista):
  soma = sum(lista)
  soma_quadrado = 0
  for i in lista:
    soma_quadrado += i ** 2
  return soma, soma_quadrado

soma, soma_quadrado = somas(x)
print(soma)
print(soma_quadrado)